---

- name: It's not DNS
  file:
    path: /etc/resolv.conf
    state: absent

- name: There's no way it's DNS
  copy:
    content: |
      nameserver 127.0.0.1
    dest: /etc/resolv.conf
    mode: '0644'

- name: It was DNS
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false