---
# tasks file for base-os

# apply base system updates
- include_tasks: updates.yml

# Setup base packages for os
- include_tasks: packages.yml

# Disable systemd-resolved for pihole
- include_tasks: dns.yml

# install tailscale
#- include_tasks: tailscale.yml
