---
# tasks file for nfs-client

- name: Install base packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - nfs-common

- name: Create mount point directory
  file:
    path: /mnt/nas
    state: directory
    mode: '0775'

- name: Mount the nfs volume on the client
  mount:
    src: prod-nas-01:/volume1/media
    path: /mnt/nas
    opts: defaults,nolock,intr
    state: mounted
    fstype: nfs
  when: inventory_hostname == "ubuntu-docker-01"